version: "2"
services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
     - "81:80"
    volumes:
     - ./:/var/www/html
    depends_on:
     - mysql
    links:
     - mysql
  mysql:
      image: mysql:5.7
      ports:
       - "3307:3306"
      environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_USER=user
       - MYSQL_PASSWORD=user
       - MYSQL_DATABASE=wordpress
      volumes:
       - ./docker/mysql:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
       - mysql
      depends_on:
       - mysql
      ports:
       - "82:80"
